#!/bin/bash
# Script to generate TypeScript API client from OpenAPI spec
# Ensures consistency between Rust backend and Vue frontend

set -e

echo "🔄 Generating TypeScript API client..."

# Install openapi-generator if not present
if ! command -v openapi-generator &> /dev/null; then
    echo "📦 Installing openapi-generator-cli..."
    npm install -g @openapitools/openapi-generator-cli
fi

# Generate client from running server
# First, start the server in background and generate spec
API_DOCS_URL="http://localhost:8080/api-docs/openapi.json"
OUTPUT_DIR="./web/src/api/generated"

echo "📥 Fetching OpenAPI spec from $API_DOCS_URL..."

# Wait for server to be ready
for i in {1..30}; do
    if curl -s "$API_DOCS_URL" > /tmp/openapi.json; then
        echo "✅ API spec downloaded"
        break
    fi
    echo "⏳ Waiting for server... ($i/30)"
    sleep 1
done

if [ ! -f /tmp/openapi.json ]; then
    echo "❌ Failed to fetch API spec. Is the server running?"
    echo "   Start the server first: ./scripts/start.sh"
    exit 1
fi

# Generate TypeScript client
echo "📝 Generating TypeScript client..."
openapi-generator generate \
    -i /tmp/openapi.json \
    -g typescript-fetch \
    -o "$OUTPUT_DIR" \
    --additional-properties=supportsES6=true,typescriptThreePlus=true

# Create index.ts barrel export
cat > "$OUTPUT_DIR/index.ts" << 'EOF'
// Auto-generated API client exports
// This file is automatically generated - DO NOT EDIT MANUALLY

export * from './models';
export * from './api';
export { Configuration } from './configuration';
EOF

echo "✅ TypeScript client generated in $OUTPUT_DIR"
echo ""
echo "📋 Next steps:"
echo "   1. Import API client in your Vue components:"
echo "      import { AgentsApi, Configuration } from '@/api/generated';"
echo "   2. Use typed API calls:"
echo "      const api = new AgentsApi(new Configuration({ basePath: '' }));"
echo "      const agents = await api.listAgents();"
