[package]
name = "system_plugin"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
sysinfo = { workspace = true }
nix = { workspace = true }
core_shared = { path = "../../shared" }
async-trait = { workspace = true }
uuid = { workspace = true }
gethostname = { workspace = true }
